---
- name: build boxfuse
  hosts: build
  become: yes
  tasks:
    - name: Ensure git package is present
      apt:
        name: git
        state: present
    - name: Ensure java packege is present
      apt:
        name: default-jdk
        state: present
    - name: Ensure maven package is present
      apt:
        name: maven
        state: present
    - name: clear /tmp
      shell: rm -rf /tmp/*
    - name: clone repository
      shell: git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
      args:
        chdir: /tmp/
    - name: build package
      shell: mvn package
      args:
        chdir: /tmp/boxfuse-sample-java-war-hello/
    - name: Get file from build
      fetch:
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: /tmp/hello.war/build/tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
        flat: yes

- name: prodakshen build
  hosts: prod
  become: yes
  tasks:
    - name: Ensure tomcat9 package is present
      apt:
        name: tomcat9
        state: present
    - name: Send file to remote
      copy:
        src: /tmp/hello.war
        dest: /var/lib/tomcat9/webapps/
        delegate_to: 'prod'
        tags: fetch
    - name: Ensure tomcat9 service is ctarted
      service:
        name: tomcat9
        state: started
