---
- name: build boxfuse
  hosts: build
  become: yes
  tasks:
    - name: Ensure git package is present
      apt:
        name: git
        state: present
    - name: Ensure java packege is present
      apt:
        name: default-jdk
        state: present
    - name: Ensure maven package is present
      apt:
        name: maven
        state: present
    - name: clear /tmp
      file:
        path: /tmp/boxfuse-sample-java-war-hello
        state: absent
    - name: clone repository
      git:
        repo: https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
        dest: /tmp
        version: master
    - name: build package
      shell: mvn package
      args:
        chdir: /tmp/boxfuse-sample-java-war-hello/
    - name: Get file from build
      fetch:
        src: /tmp/boxfuse-sample-java-war-hello/target/hello-1.0.war
        dest: tmp/hello-1.0.war
        flat: yes

- name: prodakshen build
  hosts: prod
  become: yes
  tasks:
    - name: Ensure tomcat9 package is present
      apt:
        name: tomcat9
        state: present
    - name: Send file to prod
      copy:
        src: tmp/hello-1.0.war
        dest: /var/lib/tomcat9/webapps/
        flat: yes
    - name: Ensure tomcat9 service is ctarted
      service:
        name: tomcat9
        state: started
